ci: Updated by github.com/hipagesgroup/repo-man [ci skip]

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -198,10 +198,10 @@ jobs:
                     registry_path="hipages/${DOCKER_IMAGE}"
                     docker_public_tags=("${gitsha1}" "latest")
                     # Login to docker hub
-                    echo "${DOCKERHUB_PASS}" | sudo docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
+                    echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin || { echo "docker hub login failed for ${registry_path}:${docker_tag}" ; exit 1; }
                     for docker_tag in "${docker_public_tags[@]}"; do
                       docker tag "magic-${dockerfile_number}" "${registry_path}:${docker_tag}"
-                      docker push "${registry_path}:${docker_tag}"
+                      docker push "${registry_path}:${docker_tag}" || { echo "docker push failed to ${registry_path}:${docker_tag}" ; exit 1; }
                     done
                   fi
                 else
