fix: adding push to ecr for branch back in

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -205,7 +205,7 @@ jobs:
                   registry_path="${docker_registry}/${registry_path}"
                   for docker_tag in ${docker_tags[@]}; do
                     docker tag "magic-${dockerfile_number}" "${registry_path}:${docker_tag}"
-            #                    docker push "${registry_path}:${docker_tag}" || { echo "docker push failed to ${registry_path}:${docker_tag}" ; exit 1; }
+                                docker push "${registry_path}:${docker_tag}" || { echo "docker push failed to ${registry_path}:${docker_tag}" ; exit 1; }
                   done
                 fi
 
